/**
 * Intel Summary Component
 *
 * Unified LLM-powered summary that aggregates ALL intel sources:
 * - Community reports (from IndexedDB)
 * - Web search results
 * - Weather data
 *
 * Generates ONE concise summary at the top of the Intel page.
 */

import { useState, useCallback, useEffect, useRef } from 'react';
import { Sparkles, RefreshCw, AlertCircle, Zap } from 'lucide-react';
import { LLMService, type LLMConfig } from '@/services/llm';
import { useAppStore, useReportsStore } from '@/stores';
import type { CommunityReport } from '@/stores/useReportsStore';
import type { ConditionReport } from '@/agents';

interface IntelSummaryProps {
  region: string;
}

// Formatting helpers
const SNOW_LABELS: Record<string, string> = {
  puch: 'powder',
  firn: 'corn/spring snow',
  cukier: 'sugar snow',
  szren: 'wind crust',
  beton: 'hard/icy',
  kamienie: 'rocks visible',
  mokry: 'wet snow',
};

const TRACK_LABELS: Record<string, string> = {
  przetarte: 'tracked/groomed',
  zasypane: 'fresh/covered',
  lod: 'icy',
};

function formatCommunityReport(report: CommunityReport): string {
  const date = new Date(report.timestamp).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
  });

  let info = `${report.location} (${date}): `;

  if (report.type === 'ascent' && report.ascent) {
    const track = TRACK_LABELS[report.ascent.trackStatus] || report.ascent.trackStatus;
    info += `Ascent - track ${track}`;
    if (report.ascent.gearNeeded.length > 0) {
      info += `, needs: ${report.ascent.gearNeeded.join(', ')}`;
    }
  } else if (report.type === 'descent' && report.descent) {
    const snow = SNOW_LABELS[report.descent.snowCondition] || report.descent.snowCondition;
    info += `Descent - ${snow}, ${report.descent.qualityRating}/5 stars`;
  }

  if (report.notes) {
    info += ` "${report.notes.slice(0, 50)}"`;
  }

  return info;
}

function formatWebReport(report: ConditionReport): string {
  const date = new Date(report.reportDate).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
  });

  let info = `${report.location} (${date}, ${report.sourceName}): `;

  if (report.conditions.length > 0) {
    info += report.conditions.join(', ');
  }

  // Include raw snippet if it has useful info
  if (report.summary && report.summary.length > 20) {
    // Extract key terms, avoid full summary that might be LLM-generated
    const shortSnippet = report.summary.slice(0, 80).replace(/\n/g, ' ');
    info += ` - "${shortSnippet}"`;
  }

  return info;
}

export function IntelSummary({ region }: IntelSummaryProps) {
  const [summary, setSummary] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const hasAttemptedAuto = useRef(false);

  const { config, webReports, weather } = useAppStore();
  const { getRecentReports } = useReportsStore();

  // Get all data
  const communityReports = getRecentReports(48).filter(
    (r) =>
      r.region.toLowerCase().includes(region.toLowerCase()) ||
      region.toLowerCase().includes(r.region.toLowerCase())
  );

  const hasData = communityReports.length > 0 || webReports.length > 0;

  const generateSummary = useCallback(async () => {
    if (!hasData) {
      setError('No data available to summarize');
      return;
    }

    setIsLoading(true);
    setError(null);

    const llmConfig: Partial<LLMConfig> = {
      provider: config.llmProvider,
      ollamaUrl: config.ollamaUrl,
      ollamaModel: config.ollamaModel,
      openrouterApiKey: config.openrouterApiKey,
      openrouterModel: config.openrouterModel,
    };

    const llm = new LLMService(llmConfig);

    // Build comprehensive data summary
    const dataSections: string[] = [];

    // Weather context
    if (weather) {
      dataSections.push(
        `CURRENT WEATHER: ${weather.temperature}°C, ${weather.condition}, wind ${weather.windSpeed} km/h`
      );
    }

    // Community reports
    if (communityReports.length > 0) {
      const formatted = communityReports
        .slice(0, 8)
        .map(formatCommunityReport)
        .join('\n');
      dataSections.push(`COMMUNITY REPORTS (${communityReports.length} total):\n${formatted}`);
    }

    // Web intel
    if (webReports.length > 0) {
      const formatted = webReports
        .slice(0, 5)
        .map(formatWebReport)
        .join('\n');
      dataSections.push(`WEB INTEL (${webReports.length} sources):\n${formatted}`);
    }

    const dataText = dataSections.join('\n\n');

    // Direct, no-preamble prompt
    const userPrompt = `Analyze this ski touring intel for ${region}, Poland and write 2-3 sentences about current conditions.

${dataText}

Write a direct summary starting immediately with conditions info. NO introduction phrases like "Here is" or "Based on". Just state the conditions.`;

    const systemPrompt = `You are a ski touring guide giving a quick conditions briefing. Be direct and practical. Start immediately with the key info - no introductions. Example good response: "Fresh powder above 1400m with tracked trails below. Watch for ice on north faces. Best conditions at Pilsko today."`;

    try {
      const response = await llm.prompt(userPrompt, systemPrompt, {
        signal: AbortSignal.timeout(30000),
      });

      // Clean up response - remove any preamble patterns
      let cleaned = response.trim();
      const preambles = [
        /^(here is|based on|according to|the|i |let me|summary:|conditions:)\s*/i,
        /^(ski touring conditions|current conditions|conditions in)[^.]*:\s*/i,
      ];
      for (const pattern of preambles) {
        cleaned = cleaned.replace(pattern, '');
      }
      // Capitalize first letter
      cleaned = cleaned.charAt(0).toUpperCase() + cleaned.slice(1);

      setSummary(cleaned);
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to generate summary';
      if (message.includes('Ollama') || message.includes('fetch')) {
        setError('LLM unavailable. Start Ollama or configure OpenRouter in Settings.');
      } else if (message.includes('timeout')) {
        setError('Request timed out. Try again or check LLM settings.');
      } else {
        setError(message);
      }
    } finally {
      setIsLoading(false);
    }
  }, [hasData, communityReports, webReports, weather, region, config]);

  // Auto-generate on first load if we have data
  useEffect(() => {
    if (hasData && !summary && !hasAttemptedAuto.current && !isLoading) {
      hasAttemptedAuto.current = true;
      setAutoGenerated(true);
      generateSummary();
    }
  }, [hasData, summary, isLoading, generateSummary]);

  if (!hasData) {
    return null;
  }

  return (
    <div className="bg-gradient-to-r from-purple-900/40 via-blue-900/30 to-purple-900/40 rounded-xl border border-purple-500/30 p-4">
      {/* Header */}
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-lg bg-purple-500/20 flex items-center justify-center">
            <Sparkles className="w-4 h-4 text-purple-400" />
          </div>
          <div>
            <h3 className="text-sm font-semibold text-white">AI Conditions Summary</h3>
            <p className="text-xs text-gray-500">
              {communityReports.length} reports + {webReports.length} web sources
            </p>
          </div>
        </div>
        {summary && !isLoading && (
          <button
            onClick={generateSummary}
            className="p-2 hover:bg-white/10 rounded-lg transition-colors"
            title="Refresh summary"
          >
            <RefreshCw className="w-4 h-4 text-purple-400" />
          </button>
        )}
      </div>

      {/* Loading state */}
      {isLoading && (
        <div className="flex items-center gap-3 py-2">
          <div className="relative">
            <Zap className="w-5 h-5 text-purple-400 animate-pulse" />
          </div>
          <span className="text-sm text-purple-200">Analyzing intel...</span>
        </div>
      )}

      {/* Error state */}
      {error && !isLoading && (
        <div className="space-y-2">
          <div className="flex items-start gap-2 text-amber-400">
            <AlertCircle className="w-4 h-4 flex-shrink-0 mt-0.5" />
            <span className="text-sm">{error}</span>
          </div>
          <button
            onClick={generateSummary}
            className="text-xs text-purple-400 hover:text-purple-300"
          >
            Try again
          </button>
        </div>
      )}

      {/* Summary display */}
      {summary && !isLoading && (
        <p className="text-sm text-gray-100 leading-relaxed">{summary}</p>
      )}

      {/* Generate button (only if no auto-generation happened) */}
      {!summary && !isLoading && !error && !autoGenerated && (
        <button
          onClick={generateSummary}
          className="w-full py-3 bg-purple-600/30 hover:bg-purple-600/50 rounded-lg text-sm text-purple-200 transition-colors flex items-center justify-center gap-2"
        >
          <Sparkles className="w-4 h-4" />
          Generate AI Summary
        </button>
      )}
    </div>
  );
}
